version: "3.9"

services:
  app:
    build: .
    image: pdf-rag-app:dev
    container_name: pdf_rag_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      STREAMLIT_SERVER_RUN_ON_SAVE: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
      VECTORDB_DIR: /app/data/chroma_db
      UPLOAD_DIR: /app/data/uploads
      CHOKIDAR_USEPOLLING: true  # reflect update
      GIT_PYTHON_REFRESH: quiet  # mlflow: disable mapping witn git version
    volumes:
      - .:/app
      - /app/.venv
      - ./data:/app/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data/mlruns:/app/mlruns
      - ./mlflow_data/artifacts:/app/artifacts
    command: mlflow ui --host 0.0.0.0 --port 5000 --allowed-hosts "*" --dev