version: "3.9"

services:
  app:
    build: .
    image: pdf-rag-app:dev
    container_name: pdf_rag_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      # STREAMLIT_BROWSER_SERVER_ADDRESS: "127.0.0.1"
      STREAMLIT_SERVER_RUN_ON_SAVE: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
      VECTORDB_DIR: /app/storage/vectordb
      UPLOAD_DIR: /app/data/uploads
      CHOKIDAR_USEPOLLING: true  # reflect update
    volumes:
      - .:/app
      - /app/.venv
      - ./data:/app/data