[project]
name = "pdf-rag-app"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "streamlit[pdf]",
  "langchain",
  "streamlit-pdf-viewer>=0.0.26",
  "pdfminer-six>=20251107",
  "langchain-core>=1.2.5",
  "langchain-openai>=1.1.6",
  "ruff>=0.14.10",
  "langchain-chroma>=1.1.0",
  "langchain-text-splitters>=1.1.0",
]

[dependency-groups]
dev = [
  "pytest"
]
