# PDF Data
pdf:
  doc_dir:  .data/uploads
  text_dir: .data/texts   # DEBUG for extracted texts

# Embedding settings
embedding:
  model: text-embedding-3-small  # openAI light model
  chunk_size: 1000 
  overlap: 200
  db_dir: ./data/chroma_db 

# LLM settings
llm:
  model: gpt-4o-mini  
  # search_type: mmr          
  temperature: 0.2
  k: 3
  # fetch_k: 20
  max_token: 1024
  prompt: |
    You are a professional assistant. Answer the user's question using ONLY the following context provided.
    If the answer is not contained within the context, respond with "I am sorry, but I could not find the information in the provided documents.

    Context:
    {context}

    Question: 
    {question}

    Answer: