# PDF Data
pdf:
  doc_dir:  data/uploads
  text_dir: data/texts   # DEBUG for extracted texts

# Embedding settings
embedding:
  model: text-embedding-3-small  # openAI light model
  chunk_size: 1024
  overlap: 200
  db_dir: data/chroma_db 

# Retriever
retriever:
  type: hybrid       # bm25 | vector | hybrid
  bm25:
    k: 5            # number of documents to retrieve
    tokenizer: default 
    lowercase: true
  vector:
    k: 5
    search_type: similarity   # similarity | mmr
  hybrid:
    bm25_weight: 0.3
    vector_weight: 0.7

# LLM settings for RAG
llm:
  model: gpt-4o-mini  
  # search_type: mmr          
  temperature: 0
  k: 5
  max_tokens: 1024
  prompt: |
    You are a professional assistant. Answer the user's question using ONLY the following context provided.
    If the answer is not contained within the context, respond with "I am sorry, but I could not find the information in the provided documents.

    Context:
    {context}

    Question: 
    {question}

    Answer:

# Evaluate RAG
eval:  
  llm:
    model: gpt-4o   # higher performance model
    temperature: 0
  golden_dataset: config/debug_eval_golden_dataset.json  # config/debug_eval_golden_dataset.json is just for one query
  log_dir: src/pdf_rag/rag/evals/logs
  result_dir: src/pdf_rag/rag/evals/result  # visualize comparisons of experiments

